packaging_format = 2

id = "complete_rp"
name = "complete raspi"
description.en = "To complete installation of a rapberry server"

version = "0.1~ynh1"

maintainers = ["siwinter"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/helloworld"

    [install.client_ip]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "string"
    default = "192.168.19.19"

    [install.client_privkey]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "string"
    default = "xyz"

    [install.server_adr]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "string"
    default = "192.168.19.19:8081"

    [install.server_pubkey]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "string"
    default = "xyz"
    
    [install.mosquitto]
    ask.en = "install mosquitto?"
    help.en = "rainradar"
    type = "boolean"
    default = "false"

    
    [install.wireguard]
    ask.en = "install wireguard"
    help.en = "rainradar"
    type = "boolean"
    default = "false"

    
    [install.rainradar]
    ask.en = "select apps to install"
    help.en = "rainradar"
    type = "boolean"
    default = "false"
    
    [install.serialMqtt]
    help.en = "serialMqtt"
    type = "boolean"
    default = "false"
    
    [install.vpnCtrl]
    help.en = "vpnCtrl"
    type = "boolean"
    default = "false"
    
    [install.mqtt_server]
    ask.en = "MQTT-Server Address"
    type = "string"
    default = "localhost"

    [install.mqtt_port]
    ask.en = "MQTT-Server Port"
    type = "number"
    default = "1883"

[resources]
#    [resources.system_user]

    [resources.install_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting 
    
    [resources.apt]
#    packages = "mc, mosquitto, wireguard, python3, python3-pip, python3-venv"
     packages = "mosquitto, python3, python3-pip, python3-venv"
