packaging_format = 2

id = "complete_rp"
name = "complete raspi"
description.en = "To complete installation of a rapberry server"

version = "0.1~ynh1"

maintainers = ["siwinter"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/helloworld"
    
    [install.rainradar]
    ask.en = "select apps to install"
    help.en = "rainradar"
    type = "boolean"
    default = "true"
    
    [install.petrol]
    help.en = "petrol"
    type = "boolean"
    default = "false"
    

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]
    
    [resources.permissions]
    main.url = "/"
    
    [resources.apt]
    packages = "python3, python3-pip, python3-venv"
#    packages = "mc"
